version: "3"
services:
  hub:
    image: dosel/zalenium
    logging:
      driver: "none"
    ports:
      - "4444:4444"
      - "5555:5555"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /d/docker/outputfiles/docker-compose/module-online-order:/usr/bin/docker
    command: >
      start --desiredContainers 2 
            --maxDockerSeleniumContainers 2 
            --maxTestSessions 3 
            --videoRecordingEnabled false
  module-online-order:
    image: danpopa86/selenium-docker
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=module-online-order.xml
    volumes:
      - /d/docker/outputfiles/docker-compose/module-online-order:/usr/share/proiectlicenta/test-output