version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  module-search:
    image: danpopa86/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=module-search.xml
    volumes:
      - /d/docker/outputfiles/docker-compose/module-search:/usr/share/proiectlicenta/test-output
  module-book-flight:
    image: danpopa86/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=module-book-flight.xml
    volumes:
      - /d/docker/outputfiles/docker-compose/module-book-flight:/usr/share/proiectlicenta/test-output
<<<<<<< HEAD
      
=======
>>>>>>> eddbe65cf1cd4d2686203cdcaf9acbcbf07b176e
